// generated by Fast Light User Interface Designer (fluid) version 1.0110

#ifndef fluid_example_h
#define fluid_example_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
extern "C" { Fl_Double_Window* make_window(); }
#endif
