######################################################################
# Automatically generated by qmake (2.01a) ? 9? 19 13:24:10 2020
######################################################################

TEMPLATE = app
TARGET = PbEx
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += PbEx.cpp
